apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node-deployment
spec:
  selector:
    matchLabels:
      app: appnode
  replicas: 1
  template:
    metadata:
      labels:
        app: appnode
    spec:
      containers:
      - name: appnode
        image: thirupathip/app:1
      - name: appnode1
        image: thirupathip/app:2
      - name: appnode2
        image: thirupathip/app:3
      - name: appnode3
        image: thirupathip/app:4
