apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node-deployment1
spec:
  selector:
    matchLabels:
      app: appnode1
  replicas: 1
  template:
    metadata:
      labels:
        app: appnode1
    spec:
      containers:
      - name: appnode1
        image: thirupathip/app:2
        ports:
        - containerPort: 5001
