apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node-deployment
spec:
  selector:
    matchLabels:
      app: appnode
  replicas: 1
  template:
    metadata:
      labels:
        app: appnode
    spec:
      containers:
      - name: appnode
        image: thirupathip/app:1
        arg: ["app.py"]
